# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6f6d9c520e36a8a800bdcb6e4608ae0ccf6f942d0c689037f11cfdb890f912dc2f01efd1796d1c18ff0b4aecec8b2ff592fa12ba8cbe4f81ab799cb4965060f7

test:
  secret_key_base: 824b844eae2603f5bfbfb285176d69d0c619b207b54bc4ac282ffe7889a13f97a0cc7a0d5af95af4cbcef3026ab5bef2fc1e8d2309fc33303099f2a4e3463ff9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
